Acme\HelloBundle\Entity\Picture:
    lifecycleCallbacks:
      prePersist: [ preUpload, setCreatedAtValue, setExpiresAtValue ]
      preUpdate: [ preUpload, setUpdatedAtValue ]
      postPersist: [ upload ]
      postUpdate: [ upload ]
      postRemove: [ removeUpload ]	
