parameters:
#    acme_hello.example.class: Acme\HelloBundle\Example
     acme_hello.handler.login_success_handler.class: Acme\HelloBundle\Handler\LoginSuccessHandler

services:
#    acme_hello.example:
#        class: %acme_hello.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
     acme_hello.handler.login_success_handler:
        class: %acme_hello.handler.login_success_handler.class%
        public: false
        arguments: [@router, @security.context]