<?php

namespace Acme\HelloBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * motionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class motionRepository extends EntityRepository
{
}
